### ISSUE TITLE
Баги интерфейса

### ISSUE THREAD

**Issue by wldmr-key** [daria40tim/kurs_bd#1]
По текущей версии [прототипа интерфейсов](https://github.com/daria40tim/kurs_bd/blob/master/%D0%9F%D1%80%D0%BE%D1%82%D0%BE%D1%82%D0%B8%D0%BF%20%D0%B8%D0%BD%D1%82%D0%B5%D1%80%D1%84%D0%B5%D0%B9%D1%81%D0%B0.pptx)

Проблема в том, что они появились раньше поверхностного анализа процессов предметной области. Адекватна ли суточная статистика? не поплохеет ли огурцам, если пару часов в сутки в теплице будет отрицательная температура? что делает техник? какая информация ему нужна/доступна? и т.д.
Может, я не прав и ты весь анализ провела в уме и получившиеся интерфейсы - это уже выкристаллизовавшийся результат. Или я прав?

**Comment by daria40tim** [comment]
Анализ предметной области представлен в явном виде в новых доках.
